version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12.0

    working_directory: ~/repo

    steps: # a collection of executable commands making up the 'build' job
      - checkout # pulls source code to the working directory

      - restore_cache: # ** restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run **
          key: &deps1-cache deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run: # Activate virtual environment with pip and install dependencies
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache: # ** special step to save dependency cache **
          key: *deps1-cache
          paths:
            - "venv"

      - run:
          name: Run linter
          command: |
            . venv/bin/activate
            flake8 .

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source='.' manage.py test

      - store_artifacts:
          path: .coverage
          destination: coverage

workflows:
  run_tests:
    jobs:
      - build_and_test
